### ISSUE TITLE
Create SSH key and add to github

### ISSUE THREAD

**Issue by yevgenybulochnik** [alexbulochnik/pythonpractice#1]
## Explanation
To access a remote repository, it is easier to setup ssh access than using a username and password. It is also more secure. To accomplish this the user needs to create a local ssh key typically in `.ssh` in the users `home` dir.

### Task
- [ ] Create local ssh key
- [ ] Add ssh key to github
- [ ] Clone this repo
- [ ] Review the markdown for this issue including how links to references are created

## References
- [Generating an SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
    - **NOTE:** Only work through generating an ssh key, do not add an ssh key to an ssh-agent 
- [Adding an SSH key to github](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account)
