### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by yevgenybulochnik** [alexbulochnik/pythonpractice#2]
For this issue, the readme needs to be updated. 

## Tasks
- [ ] Update the readme header so it is cased correctly and add space
- [ ] Add a random paragraph about how much you like python :)
- [ ] Commit the change locally
- [ ] Push the commit to github

## References
- [git commits](https://www.atlassian.com/git/tutorials/saving-changes)

**Comment by yevgenybulochnik** [comment]
More references on markdown
- [Github Flavored Markdown](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
